### ISSUE TITLE
请求直接发布二进制版……

### ISSUE THREAD

**Issue by doylecnn** [BroncoTc/PySocketCoolQ#1]
手上没有e语言的编译工具。而易语言编译期本身也不是免费软体……所以请求直接发布二进制版……

**Comment by broncotc** [comment]
争取今晚再修点细节然后开第一个release，现在自习课下课了。。。

**Comment by doylecnn** [comment]
我之前用c语言自己写了个udp socket 不稳定
然后用c+libuv 撸了一个……更不稳定
所以看到有e语言大神出来撸了个socket 真是太高兴了……

**Comment by broncotc** [comment]
二进制文件以发布进入release

**Comment by BroncoTc** [comment]
二进制文件以发布进入release
