### ISSUE TITLE
Make ELang more easy to read from non-ELang IDE

### ISSUE THREAD

**Issue by liushuyu** [BroncoTc/PySocketCoolQ#5]
As the ELang project file is a binary one,  and therefore it is not convience to read without the (only) paid IDE. My suggestion is that create some plain text documents(txt file encoded in UTF-8) and put your module code in them.
FYI, here is an example: https://github.com/xiwo4525/AGE-Taiko

Thx

**Comment by broncotc** [comment]
wow such a great idea

**Comment by liushuyu** [comment]
> wow such a great idea

so interesting !!
well?

**Comment by broncotc** [comment]
The newest commit now included the complete source code of the elang part

**Comment by liushuyu** [comment]
BTW, you can close an issue via a commit by using keywords like "closes" "resolves" "fixes"
FYI, For example: You can close this issue via a commit with the commit message like:

```
add text version for ELang source code

closes #5
```
